name: Deploy Java Backend to Appengine

on:
  push:
    branches:
      - master

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8]
    name: Java ${{ matrix.java }} compile then deploy
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Authenticate into Google Cloud Platform
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '275.0.0'
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      - uses: actions/checkout@v1
      - name: Use Node.js 12.8
        uses: actions/setup-node@v1
        with:
          node-version: 12.8

      - name: Install Angular
        run: npm install -g @angular/cli

      - name: Install Angular Dep.
        run: cd mediaphile && npm install

      - name: Test Angular Application
        run: cd mediaphile && ng test --watch=false --browsers=ChromeHeadlessCustom

      - name: Build Angular Application
        run: cd mediaphile && ng b --prod

      - name: Write value to Properties-file
        uses: christian-draeger/write-properties@1.0.0
        with:
          path: './src/main/resources/config.properties'
          property: 'movie_apikey'
          value: ${{secrets.MOVIE_APIKEY}}

      - name: Publish app to Google App Engine
        run: |
          gcloud config set project kirankubetest2
          mvn clean package appengine:deploy